### PR TITLE
Add app_type and app_version to error reports

### PR DESCRIPTION
**Pull request by kaelumania**

### CODE REVIEW

**Comment by kaelumania** [comment]
@jarednorman any review on this PR? Would love to see this merged.

**Comment by kaelumania** [comment]
@jarednorman ping

**Comment by grantovich** [comment]
Hi @kaelumania, just getting to some of these old PRs, sorry for the delay 😅 This is great, although I think we'd want to support `app_type` and `app_version` primarily as global configuration rather than per-report configuration. I believe all that's needed for this is to put the defaults in the `default_config` function in `bugsnag.ex` rather than in the `fetch_option` calls. And of course, we'd want to update the README to indicate the new options.

If there's an easy way to do so, I'd also love to have the default value for `app_version` be set to the current project's app version. No pressure to include that, though!

**Comment by grantovich** [comment]
Superseded by #70.

**Pull request closed without merging**
