### PR TITLE
Consolidated config & supervision improvements

### PR DESCRIPTION
**Pull request by mootpointer**
This PR merges together #35, #33 and #31

The plan is to merge this and then shoot for a beta release tomorrow.

### CODE REVIEW

**Comment by driv3r** [comment]
actually I would suggest using this lib for config, till there's something built in within the language - [config_ext](https://github.com/driv3r/config_ext). I find more and more applications for it, especially in dynamic environments like docker based (AWS ECS, Kubernetes, etc). WDYS?

**Comment by mootpointer** [comment]
@driv3r I'd prefer not to push back a release much longer – how about I land this PR and we look at it down the line?

**Comment by mootpointer** [comment]
Closes #31.
Closes #33.
Closes #35

**Comment by driv3r** [comment]
@mootpointer :+1:

**Pull request merged**
