### PR TITLE
Update bugsnag.ex

### PR DESCRIPTION
**Pull request by arcz**
Fix `warning: undefined behaviour function start/2 (for behaviour Application)`

### CODE REVIEW

**Comment by mootpointer** [comment]
Looks good, we'll just need to fix up `test_helper.exs` which calls the old `Bugsnag.start/0` function.

**Comment by arcz** [comment]
Yeah, you are right. I'm wondering if this call is even needed in `test_helper.exs`. What do you think?

**Comment by mootpointer** [comment]
On reflection, you're right. The only reason it needed to be called explicitly was because it was the wrong arity. 




On Thu, Jul 21, 2016 at 12:39 AM +1000, "Artur Cygan" <notifications@github.com> wrote:












Yeah, you are right. I'm wondering if this call is even needed in test_helper.exs. What do you think?

**Comment by arcz** [comment]
Updated, seems that it fixed the issue.

**Pull request merged**
