### PR TITLE
Clarify usage of Bugsnag.Logger in the README

### LINKED ISSUE #27: How to use the Bugsnag.Logger?
I'm trying to send unexpected errors (such as when a process dies) to bugsnag. Is that possible with `Bugsnag.Logger`? If not how would I go about it?

I've set bugsnag up like this in my config:

    config :bugsnag, api_key: System.get_env("BUGSNAG_API_KEY")
    config :bugsnag, release_stage: "#{Mix.env}"
    config :bugsnag, use_logger: true

Is that the right way to enable `Bugsnag.Logger`? Also how can I simulate/trigger an error that `Bugsnag.Logger` will send? I've tried sending an unknown message to a process, but the resulting error does not match the pattern for `handle_event({:error_report, _gl, {_pid, _type, [message | _]}}, state) when is_list(message)`.

### PR DESCRIPTION
**Pull request by vorce**
Close #27

### CODE REVIEW

**Comment by mootpointer** [comment]
Brilliant. Thanks!

**Comment by mootpointer** [comment]
Just out of interest, this behaviour should have happened if you included `:bugsnag` in your list of applications in `mix.exs`. Was this not the case?

**Comment by vorce** [comment]
@mootpointer No that is not the case. I expected that too. Probably something to look into!

**Comment by mootpointer** [comment]
Ah. Whoops. I merged in another PR which has created a conflict. Would you be willing to rebase on top of master and I'll get this merged in?

**Comment by vorce** [comment]
done

**Pull request merged**
